Module4 task1
htmlacademy-ecmascript/799907-big-trip-12 pull request #6
Opened 2020-08-19 16:36 UTC by nataliiakutsovol

2020-08-19 16:48 UTC, ant1quar requested changes

2020-08-19 16:48 UTC, ant1quar commented on src/const.js
> +  text: [`Taxi`, `Bus`, `Train`, `Ship`, `Transport`, `Drive`, `Flight`],
Тут не нужно дублировать текст - есть toLowerCase, который сделает то, что нужно

2020-08-19 16:48 UTC, ant1quar commented on src/const.js
> +  labelClass: [`event__type-label--taxi`, `event__type-label--bus`, `event__type-label--train`, `event__type-label--ship`, `event__type-label--transport`, `event__type-label--drive`, `event__type-lab
много повторений `event__type-label` введи глобальный CSS-класс на уровне компоненты

2020-08-19 16:48 UTC, ant1quar commented on src/const.js
> +  id: [`event-type-taxi-1`, `event-type-bus-1`, `event-type-train-1`, `event-type-ship-1`, `event-type-transport-1`, `event-type-drive-1`, `event-type-flight-1`],
И это тоже можно спроектировать через value, задав `event-type-${value}-1`

2020-08-19 16:48 UTC, ant1quar commented on src/const.js
> +};
То же самое, что и для transferObj

2020-08-19 16:48 UTC, ant1quar commented on src/main.js
> +render(menuContainer, new AcceptFiltersBtn().getElement(), renderPosition.BEFOREEND);
Глянул я тут на `render` и можно куда проще и чище.
у тебя всего 2 места, куда можно воткнуть элемент, зачем тебе отдельная структура `renderPosition`?
можно переписать функцию render следующим образом
```
export const render = (container, element, isAfterBegin = false) => {
if(isAfterBegin) вставляем сначала
else вставляем с конца.
}
```
Это позволит вызывать вот так 
```

render(tripCounterContainer, new TripCounter().getElement(), true);
render(menuContainer, new Menu().getElement());
```

2020-08-19 16:48 UTC, ant1quar commented on src/view/buttons.js
>  };
Думаю эту функцию и подобные можно вообще удалить. а саму верстку засунуть прямо в класс. 
Я, вроде писал это в учебном проекте

2020-08-19 16:48 UTC, ant1quar commented on src/view/edit-trip/edit-trip-container.js
> +    this._trip = trip || BLANK_TRIP;
Не совсем верно, если трип пустой, мы должны никакую верстку не генерить вообще

2020-08-25 09:47 UTC, nataliiakutsovol commented on src/main.js
> +render(menuContainer, new AcceptFiltersBtn().getElement(), renderPosition.BEFOREEND);
а если afterend (у меня есть один такой кейс)?

2020-08-26 14:12 UTC, ant1quar commented on src/main.js
> +render(menuContainer, new AcceptFiltersBtn().getElement(), renderPosition.BEFOREEND);
а все равно, что пока только один. их может быть много в последствии)

2020-08-26 20:04 UTC, merged